version: '3.1'

services:
  db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ZABBIX_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ZABBIX_MYSQL_DATABASE}
      MYSQL_USER: ${ZABBIX_MYSQL_USER}
      MYSQL_PASSWORD: ${ZABBIX_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  zabbix_server:
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: ${ZABBIX_DB_HOST}
      MYSQL_USER: ${ZABBIX_MYSQL_USER}
      MYSQL_DATABASE: ${ZABBIX_MYSQL_DATABASE}
      MYSQL_PASSWORD: ${ZABBIX_DB_PASSWORD}
    ports:
      - "10051:10051"

  zabbix_frontend:
    image: zabbix/zabbix-web-apache-mysql:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: ${ZABBIX_DB_HOST}
      MYSQL_USER: ${ZABBIX_MYSQL_USER}
      MYSQL_PASSWORD: ${ZABBIX_DB_PASSWORD}
      ZBX_SERVER_HOST: ${ZABBIX_ZBX_SERVER_HOST}
      PHP_TZ: ${ZABBIX_PHP_TZ}
    ports:
      - "80:8080"
      - "443:8443"

volumes:
  mysql-data:
    external: true
